obj-y += dal.o
ifndef CONFIG_ARCH_HTCLEO
obj-y += q6audio_htcleo.o
else
obj-y += q6audio.o
endif
obj-y += pcm_out.o
obj-y += pcm_in.o
obj-y += mp3.o
obj-y += routing.o
obj-y += audio_ctl.o
obj-y += msm_q6vdec.o
obj-y += msm_q6venc.o
obj-y += aac_in.o
obj-y += qcelp_in.o
